spring:
  application:
    name: KryptoBot
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name:  org.h2.Driver
    username: sa
    password:
  main:
    lazy-initialization: false


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

# Telegram Bot Configuration
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

logging:
  level:
    org.springframework.boot.context.properties: DEBUG